"""adds one-to-many relationship between festival and user that created it

Revision ID: 60d6ca223fc8
Revises: aef4626bdd1f
Create Date: 2023-10-03 08:12:23.693382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d6ca223fc8'
down_revision = 'aef4626bdd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_festivals_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_festivals_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
