"""Adds spotify_id column to Artist

Revision ID: aef4626bdd1f
Revises: 4aa975edf57e
Create Date: 2023-10-02 22:14:52.428451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef4626bdd1f'
down_revision = '4aa975edf57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
